import { ExperienceYears } from "../../types";

export const experienceYears: ExperienceYears = {
  years: [
    {
      year: "2021",
      experiences: [
        {
          imageAlt: "mHealth Lab Logo",
          companyName: "Northeastern University MHealth Research Lab",
          jobTitle: "Research Assistant",
          startDate: "March 2021",
          endDate: "Nov 2022",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
      ],
    },
    {
      year: "2022",
      experiences: [
        {
          imageAlt: "Khoury College of Computer Science Logo",
          companyName: "Khoury College of Computer Sciences",
          jobTitle: "Teaching Assistant - Fundamentals of Computer Science 2",
          startDate: "Jan 2022",
          endDate: "July 2022",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
        {
          imageAlt: "HackBeanpot Logo",
          companyName: "HackBeanpot",
          jobTitle: "Software Engineer",
          startDate: "Apr 2022",
          endDate: "Apr 2023",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
        {
          imageAlt: "Clora Logo",
          companyName: "Clora",
          jobTitle: "Software Development Engineer Intern",
          startDate: "July 2022",
          endDate: "Dec 2022",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
      ],
    },
    {
      year: "2023",
      experiences: [
        {
          imageAlt: "Khoury College of Computer Science Logo",
          companyName: "Khoury College of Computer Sciences",
          jobTitle: "Professional Development for Co-op Teaching Assistant",
          startDate: "Jan 2023",
          endDate: "May 2023",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
        {
          imageAlt: "HackBeanpot Logo",
          companyName: "HackBeanpot",
          jobTitle: "Co-Executive Director",
          startDate: "Apr 2023",
          endDate: "Apr 2024",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
        {
          imageAlt: "Clora Logo",
          companyName: "Clora",
          jobTitle: "Software Development Engineer Intern",
          startDate: "May 2023",
          endDate: "June 2023",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
        {
          imageAlt: "Flexcar Logo",
          companyName: "Flexcar",
          jobTitle: "Software Development Engineer Intern",
          startDate: "July 2023",
          endDate: "Jan 2024",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
      ],
    },
    {
      year: "2024",
      experiences: [
        {
          imageAlt: "Khoury College of Computer Science Logo",
          companyName: "Khoury College of Computer Sciences",
          jobTitle: "Professional Development for Co-op Teaching Assistant",
          startDate: "Jan 2024",
          endDate: "May 2024",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
        {
          imageAlt: "Flexcar Logo",
          companyName: "Flexcar",
          jobTitle: "Software Development Engineer 1 - Part Time",
          startDate: "Jan 2024",
          endDate: "July 2024",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
        {
          imageAlt: "Flexcar Logo",
          companyName: "Flexcar",
          jobTitle: "Software Development Engineer 1",
          startDate: "July 2024",
          endDate: "Present",
          location: "Boston, MA",
          description: "Fill this in with actual description",
        },
      ],
    },
  ],
};
