import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { NavigationBar } from "@/design-system/src/navigation-bar/NavigationBar";
import { NavigationBarContainer } from "@/design-system/src/navigation-bar/NavigationBarContainer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
      <NavigationBarContainer/>
      </body>
    </html>
  );
}
