import type { Metadata } from "next";
import "./globals.css";
import { ToastProvider } from "@/design-system/src/provider/ToastProvider";
import { Analytics } from "@vercel/analytics/react"

export const metadata: Metadata = {
  title: "Dhivas Sugumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body className="bg-neutral0">
        <ToastProvider />
        <Analytics />
      </body>
    </html>
  );
}
