import type { Metadata } from "next";
import "./globals.css";
import { NavigationBarContainer } from "@/design-system/src/navigation-bar/NavigationBarContainer";

export const metadata: Metadata = {
  title: "Dhivas Sugumar",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        {children}
        <NavigationBarContainer />
      </body>
    </html>
  );
}
